/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_base_de_datos.Administrador;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.button.StandardButtonShaper;
import org.jvnet.substance.utils.SubstanceConstants;
import org.jvnet.substance.watermark.SubstanceImageWatermark;
import proyecto_base_de_datos.Clientes.Cajones_en_uso_Admin;
import proyecto_base_de_datos.Conector;
import proyecto_base_de_datos.Encargado.Cajones_en_uso;

/**
 *
 * @author samuel
 */
public class Registro_Empleado extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Empleado
     */
    public Registro_Empleado() {

        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro de empleados");
        JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteGlassSkin");
        //     SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceEbonyTheme");

        SubstanceLookAndFeel.setCurrentWatermark(new SubstanceImageWatermark("src\\Images\\User2.png"));
        SubstanceLookAndFeel.setImageWatermarkOpacity(new Float(0.1));
        this.registro.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.registro.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.BOTTOM);
        this.registro.putClientProperty(SubstanceLookAndFeel.BUTTON_OPEN_SIDE_PROPERTY, SubstanceConstants.Side.BOTTOM);
        ValidaJTextField(nombre, 1, 30);
        ValidaJTextField(aP, 5, 20);
        ValidaJTextField(aM, 5, 20);
        ValidaJTextField(sueldo, 3, 20);
    }

    Registro_Empleado(Ganancias aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/2.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        turno3 = new javax.swing.JTextField();
        hEn = new javax.swing.JComboBox<>();
        registro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sueldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        aM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aP = new javax.swing.JTextField();
        turno2 = new javax.swing.JTextField();
        cargo1 = new javax.swing.JComboBox<>();
        turno1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        hSal = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel2.setText("Apellido paterno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel3.setText("Apellido materno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel7.setText("Sueldo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        nombre.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 240, -1));

        turno3.setEditable(false);
        turno3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        turno3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(turno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 160, -1));

        hEn.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        hEn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00", "16:00" }));
        hEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hEnActionPerformed(evt);
            }
        });
        jPanel1.add(hEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 170, -1));

        registro.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        registro.setText("Registro");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel1.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel8.setText("Cargo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        sueldo.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        sueldo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 240, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel9.setText("Día de Turno 2:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        aM.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jPanel1.add(aM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, -1));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel10.setText("Horario Entrada:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel11.setText("Día de Turno 3:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel12.setText("Día de Turno:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        aP.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jPanel1.add(aP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, -1));

        turno2.setEditable(false);
        turno2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        turno2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(turno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, -1));

        cargo1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        cargo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seguridad", "Administración" }));
        jPanel1.add(cargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 260, -1));

        turno1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        turno1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        turno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turno1ActionPerformed(evt);
            }
        });
        jPanel1.add(turno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel13.setText("Horario Salida:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        hSal.setEditable(false);
        hSal.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        hSal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(hSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ajustes.png"))); // NOI18N
        jMenu1.setText("Opciones");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/E.png"))); // NOI18N
        jMenuItem3.setText("Estado de estacionamiento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D.png"))); // NOI18N
        jMenuItem1.setText("Ganacias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/er.png"))); // NOI18N
        jMenuItem2.setText("Horario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bote.png"))); // NOI18N
        jMenuItem4.setText("Baja Empleado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
        emp=new Empleado();
        if (nombre.getText().isEmpty() || aP.getText().isEmpty() || aM.getText().isEmpty() || sueldo.getText().isEmpty() || turno2.getText().isEmpty() || turno3.getText().isEmpty() || hSal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Porfavor, verifique que todos los campos hayan sido llenados");
        } else {
            emp.setName(nombre.getText()); 
            emp.setaPat(aP.getText()); 
            emp.setaMat(aM.getText());
            emp.setCargo((String) cargo1.getSelectedItem());
            emp.setDia((String) turno1.getSelectedItem());
            emp.setDia2(turno2.getText());
            emp.setDia3(turno3.getText());
            emp.sethEntrada((String) hEn.getSelectedItem());
            emp.sethSalida(hSal.getText());
            emp.setSuel(Integer.parseInt(sueldo.getText()));
            emp.setID((int) Math.floor(Math.random() * (999 - 100 + 1) + 100));
            System.out.println(emp);
            con.EjecutarActualizacion("call setEmpleado( " + emp.toString() + " );");
            JOptionPane.showMessageDialog(null, "Empleado registrado con éxito con el ID: " + emp.getID());
            nombre.setText("");
            aP.setText("");
            aM.setText("");
            turno2.setText("");
            turno3.setText("");
            hSal.setText("");
            sueldo.setText("");
        }
    }//GEN-LAST:event_registroActionPerformed

    private void turno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turno1ActionPerformed
        // TODO add your handling code here:
        switch ((String) turno1.getSelectedItem()) {
            case lun:
                turno2.setText(mie);
                turno3.setText(vie);
                break;
            case mar:
                turno2.setText(jue);
                turno3.setText(sab);
                break;
            case mie:
                turno2.setText(vie);
                turno3.setText(dom);
                break;
            case jue:
                turno2.setText(sab);
                turno3.setText(lun);
                break;
            case vie:
                turno2.setText(dom);
                turno3.setText(mar);
                break;
            case sab:
                turno2.setText(lun);
                turno3.setText(mie);
                break;
            case dom:
                turno2.setText(mar);
                turno3.setText(jue);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_turno1ActionPerformed

    private void hEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hEnActionPerformed
        // TODO add your handling code here:
        switch ((String) hEn.getSelectedItem()) {
            case "8:00":
                hSal.setText("16:00");
                break;
            case "16:00":
                hSal.setText("00:00");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_hEnActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Baja_Empleado op4= new Baja_Empleado();
         op4.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Horario opc3 = new Horario();
        opc3.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int ID = Ganancias.ID;
        Ganancias opc2 = new Ganancias(ID);
        opc2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int ID = Ganancias.ID;
        Cajones_en_uso_Admin opc1 = new Cajones_en_uso_Admin(ID);
        opc1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void ValidaJTextField(JTextField txt, int TipoValidacion, int LongitudMax) {
        txt.addKeyListener(
                new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (txt.getText().length() == LongitudMax) {
                    e.consume();
                    return;
                }
                char c = e.getKeyChar();
                switch (TipoValidacion) {
                    case 1:
                        if (!(Character.isLetter(c)) && !(Character.isSpaceChar(c))) {
                            e.consume();
                        }
                        break;
                    case 5:
                        if (!(Character.isLetter(c)) || (Character.isSpaceChar(c))) {
                            e.consume();
                        }
                        break;
                    case 2:
                        if (!(Character.isDigit(c))) {
                            e.consume();
                        }
                        break;
                    case 3:
                        if (!(Character.isDigit(c)) || Character.isSpaceChar(c)) {
                            e.consume();
                        }
                        break;
                    case 4:
                        if (!(Character.isLetter(c)) && !(Character.isDigit(c)) && Character.isSpaceChar(c)) {
                            e.consume();
                        }
                        break;
                    default:
                        break;
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        }
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aM;
    private javax.swing.JTextField aP;
    private javax.swing.JComboBox<String> cargo1;
    private javax.swing.JComboBox<String> hEn;
    private javax.swing.JTextField hSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton registro;
    private javax.swing.JTextField sueldo;
    private javax.swing.JComboBox<String> turno1;
    private javax.swing.JTextField turno2;
    private javax.swing.JTextField turno3;
    // End of variables declaration//GEN-END:variables
    private final String lun = "Lunes";
    private final String mar = "Martes";
    private final String mie = "Miércoles";
    private final String jue = "Jueves";
    private final String vie = "Viernes";
    private final String sab = "Sábado";
    private final String dom = "Domingo";
    private Empleado emp;
    private Conector con=new Conector();
}
