/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_base_de_datos.Clientes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import proyecto_base_de_datos.Encargado.*;
import proyecto_base_de_datos.*;
import java.util.ArrayList;
import static javax.management.timer.Timer.ONE_SECOND;
import javax.swing.Timer;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.watermark.SubstanceImageWatermark;
import proyecto_base_de_datos.Administrador.Baja_Empleado;
import proyecto_base_de_datos.Administrador.Ganancias;
import proyecto_base_de_datos.Administrador.Horario;
import proyecto_base_de_datos.Administrador.Registro_Empleado;

/**
 *
 * @author samue
 */
public class Cajones_en_uso_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Cajones_en_uso
     */
    public Cajones_en_uso_Admin(int ID) {
        con = new Conector();
        initComponents();
        this.setLayout(null);
        this.ID = ID;
        //initArray();
        setClock();
        initArray();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Vista de Seguridad");
        IDemp.setText(String.valueOf(ID));
        String name, apPat, apMat;
        System.out.println(ID);
        name = con.getValor("select nombre from empleado where idEmp=" + ID + " ;");
        apPat = con.getValor("select ap from empleado where idEmp=" + ID + " ;");
        apMat = con.getValor("select am from empleado where idEmp=" + ID + " ;");
        Nombre.setText(name);
        aP.setText(apPat);
        aM.setText(apMat);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteGlassSkin");
        //SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceEbonyTheme");
        SubstanceLookAndFeel.setCurrentWatermark(new SubstanceImageWatermark("src\\Imagenes\\llantaG_1.png"));
        SubstanceLookAndFeel.setImageWatermarkOpacity(new Float(0.1));
        timer = new Timer(10000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizar.doClick();
            }
        });
        timer.start();

    }

    private void setClock() {
        this.add((new clock(1030, 100, "labelClock")).getLbl());
    }

    private void initArray() {
        arr = new ArrayList<>();
        int i;
        for (i = 0; i != 20; i++) {
            arr.add(new ArrLabels(20 + (i * 50), 20, "A" + i, false, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 20; i != 40; i++) {
            arr.add(new ArrLabels(20 + ((i - 20) * 50), 100, "B" + (i - 20), true, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 40; i != 60; i++) {
            arr.add(new ArrLabels(20 + ((i - 40) * 50), 250, "C" + (i - 40), false, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 60; i != 80; i++) {
            arr.add(new ArrLabels(20 + ((i - 60) * 50), 330, "D" + (i - 60), true, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 80; i != 100; i++) {
            arr.add(new ArrLabels(20 + ((i - 80) * 50), 480, "E" + (i - 80), false, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 100; i != 120; i++) {
            arr.add(new ArrLabels(20 + ((i - 100) * 50), 560, "F" + (i - 100), true, i + 1));
            this.add(arr.get(i).getLbl());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IDemp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        aP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        aM = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lf.png"))); // NOI18N
        jLabel1.setAlignmentY(40.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 391, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lf.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lf.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 498, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lane_lines.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lane_lines.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setText("Apellido M.:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, 70, 40));

        IDemp.setEditable(false);
        getContentPane().add(IDemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 80, -1));

        jLabel8.setText("ID empleado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, -1, 40));

        Nombre.setEditable(false);
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, 80, -1));

        jLabel9.setText("Nombre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 280, 50, 40));

        aP.setEditable(false);
        getContentPane().add(aP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 80, -1));

        jLabel10.setText("Apellido P.:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 328, 70, 40));

        aM.setEditable(false);
        getContentPane().add(aM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 80, -1));

        actualizar.setText("Actualizar Vista");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, -1, -1));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ajustes.png"))); // NOI18N
        jMenu3.setText("Opciones");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/er.png"))); // NOI18N
        jMenuItem3.setText("Horario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D.png"))); // NOI18N
        jMenuItem2.setText("Ganancias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ADP.png"))); // NOI18N
        jMenuItem1.setText("Registro de Personal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Baja Empleado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int ID = Ganancias.ID;
        Ganancias op2 = new Ganancias(ID);
        op2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Registro_Empleado op3 = new Registro_Empleado();
        op3.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Horario op1 = new Horario();
        op1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:}
        int i;
        for (i = 0; i < 120; i++) {
            arr.get(i).updateView(i + 1);
        }
        System.out.println("Boton Presionado");
    }//GEN-LAST:event_actualizarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Baja_Empleado op4= new Baja_Empleado();
         op4.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDemp;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField aM;
    private javax.swing.JTextField aP;
    private javax.swing.JButton actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
    private ArrayList<ArrLabels> arr;
    private int ID;
    private Conector con;
    private Timer timer;

}
