/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_base_de_datos.Clientes;

import proyecto_base_de_datos.Conector;

/**
 *
 * @author samue
 */
public class Genera_Boleto extends javax.swing.JDialog {
    private int ID;
    /**
     * Creates new form Genera_Boleto
     */
    public Genera_Boleto(java.awt.Frame parent, boolean modal,String idub,int idCajon) {
        super(parent, modal);
        this.setTitle("Boleto");
        initComponents();
        ub.setText(idub);
        ID=idCajon;
        initTicket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ub = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tarifa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        noBoleto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(624, 403));
        setPreferredSize(new java.awt.Dimension(626, 426));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ub.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        ub.setText("jTextField1");
        ub.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(ub, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 105, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 163, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/custom_button.png"))); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setMargin(new java.awt.Insets(5, 10, 5, 5));
        jButton1.setPreferredSize(new java.awt.Dimension(138, 69));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 110, 60));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setText("UBICACIÓN:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setText("HORA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 30));

        hora.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        hora.setText("jTextField1");
        hora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 255, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setText("FECHA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 30));

        fecha.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        fecha.setText("jTextField1");
        fecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 175, 140, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setText("TARIFA/HORA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 130, 30));

        tarifa.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        tarifa.setText("jTextField1");
        tarifa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 335, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. de Boleto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 30));

        noBoleto.setBackground(new java.awt.Color(102, 102, 255));
        noBoleto.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        noBoleto.setForeground(new java.awt.Color(255, 255, 255));
        noBoleto.setText("jTextField1");
        noBoleto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        noBoleto.setFocusable(false);
        noBoleto.setRequestFocusEnabled(false);
        noBoleto.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(noBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boleto.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Uso next=new Uso();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void initTicket(){
        Conector con=new Conector();
        noBoleto.setText(con.getValor("select idUs from tiempo where idUb="+this.ID+" ;"));
        fecha.setText(con.getValor("select fecha from tiempo where idUb="+this.ID+" ;"));
        hora.setText(con.getValor("select hLlegada from tiempo where idUb="+this.ID+" ;"));
        tarifa.setText("$15");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField noBoleto;
    private javax.swing.JTextField tarifa;
    private javax.swing.JTextField ub;
    // End of variables declaration//GEN-END:variables
}
