/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_base_de_datos.Clientes;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import org.jvnet.substance.*;
/**
 *
 * @author samuel
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jvnet.substance.button.StandardButtonShaper;
import org.jvnet.substance.utils.SubstanceConstants;
import org.jvnet.substance.watermark.SubstanceImageWatermark;
import parkinglot.ArrLabelAndChecks;
import parkinglot.ParkingView;
import parkinglot.Time;
import proyecto_base_de_datos.Conector;

public class Pago extends javax.swing.JFrame {

    /**
     * Creates new form Pago
     */
    public Pago() {
        initComponents();
        //this.jbtregistro1.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY,SubstanceConstants.Side.LEFT);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Pago del cliente");
        this.jButton1.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.setVisible(true);

    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/2.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        noBoleto = new javax.swing.JTextField();
        hOc = new javax.swing.JLabel();
        cajon = new javax.swing.JLabel();
        pago = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        b3 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        bBack = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b0 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setText("Cobro Estacionamiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel2.setText("No. Boleto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel3.setText("Cajon");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel4.setText("Horas ocupadas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jLabel5.setText("Total a pagar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 90, 70));

        noBoleto.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jPanel1.add(noBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, 24));

        hOc.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        hOc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(hOc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, 24));

        cajon.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        cajon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 110, 24));

        pago.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        pago.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 110, 24));

        jButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b3.png"))); // NOI18N
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b3MousePressed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1.png"))); // NOI18N
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b1(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.png"))); // NOI18N
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b2MousePressed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b4.png"))); // NOI18N
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b4MousePressed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b5.png"))); // NOI18N
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b5MousePressed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b6.png"))); // NOI18N
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b6MousePressed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b7.png"))); // NOI18N
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b7MousePressed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        bBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bBack.png"))); // NOI18N
        bBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bBackMousePressed(evt);
            }
        });
        jPanel1.add(bBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b9.png"))); // NOI18N
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b9MousePressed(evt);
            }
        });
        jPanel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b8.png"))); // NOI18N
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b8MousePressed(evt);
            }
        });
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        b0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b0.png"))); // NOI18N
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b0MousePressed(evt);
            }
        });
        jPanel1.add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "0");
        }
    }//GEN-LAST:event_b0MousePressed

    private void b8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "8");
        }
    }//GEN-LAST:event_b8MousePressed

    private void b9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "9");
        }
    }//GEN-LAST:event_b9MousePressed

    private void bBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBackMousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() != 0) {
            noBoleto.setText(noBoleto.getText().substring(0, noBoleto.getText().length() - 1));
        }
    }//GEN-LAST:event_bBackMousePressed

    private void b7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "7");
        }
    }//GEN-LAST:event_b7MousePressed

    private void b6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "6");
        }
    }//GEN-LAST:event_b6MousePressed

    private void b5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "5");
        }
    }//GEN-LAST:event_b5MousePressed

    private void b4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "4");
        }
    }//GEN-LAST:event_b4MousePressed

    private void b2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "2");
        }
    }//GEN-LAST:event_b2MousePressed

    private void b1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1
        // TODO add your handling code here
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "1");
        }
    }//GEN-LAST:event_b1

    private void b3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MousePressed
        // TODO add your handling code here:
        if (noBoleto.getText().length() < 4) {
            noBoleto.setText(noBoleto.getText() + "3");
        }
    }//GEN-LAST:event_b3MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cajon.getText().isEmpty() == false) {
            con.EjecutarActualizacion("update usuario set status=0 where idUs=" + noBoleto.getText() + " ;");
            con.EjecutarActualizacion("update cajon set disponible=0 where idUb=(select idUb from  usuario u, tiempo t where u.idUs=" + noBoleto.getText() + " and u.idUs=t.idUs and t.idUb=idUb);");
            con.EjecutarActualizacion("insert into ganancia values(" + noBoleto.getText() + " , " + tiempo.getDia() + " , " + pay + " );");
            Uso next = new Uso();
            next.setVisible(true);
            dispose();
        }
        else 
            JOptionPane.showMessageDialog(null, "Porfavor seleccione un boleto para pagar");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int idCajon;
        ParkingView aux = new ParkingView();
        ArrayList<ArrLabelAndChecks> arrAux;
        arrAux = aux.getArray();
        if (noBoleto.getText().isEmpty() || noBoleto.getText().length() != 4 || con.ExisteEnBD("select idUs from usuario where idUs=" + noBoleto.getText() + " ;") == false || con.getValor("select status from usuario where idUs=" + noBoleto.getText() + " ;").equals("0")) {
            JOptionPane.showMessageDialog(null, "El número de boleto introducido es incorrecto");
        } else if (con.getValor("select status from usuario where idUs=" + noBoleto.getText() + " ;").equals("1")) {
            Time tiempo = new Time();
            con.EjecutarActualizacion("call setTimeSalida(" + tiempo.getHora() + " , " + noBoleto.getText() + " );");
            System.out.println(noBoleto.getText());
            idCajon = Integer.parseInt(con.getValor("select idUb from tiempo where idUs=" + noBoleto.getText() + " ;"));
            System.out.println(idCajon);
            cajon.setText(arrAux.get(idCajon - 1).getName());
            con.EjecutarActualizacion("call setLapso(" + noBoleto.getText() + ");");
            hOc.setText(con.getValor("select lapso from tiempo where idUs=" + noBoleto.getText() + " ;"));
            con.EjecutarActualizacion("call updatePago(" + noBoleto.getText() + ");");
            pay = con.getValor("select pago from usuario where idUs=" + noBoleto.getText() + ";");
            pago.setText("$" + pay);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        Uso newUso=new Uso();
        newUso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b0;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JLabel bBack;
    private javax.swing.JLabel cajon;
    private javax.swing.JLabel hOc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField noBoleto;
    private javax.swing.JLabel pago;
    // End of variables declaration//GEN-END:variables
    Conector con = new Conector();
    private String pay;
    Time tiempo = new Time();
}
