/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_base_de_datos.Encargado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import proyecto_base_de_datos.*;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author samue
 */
public class Cajones_en_uso extends javax.swing.JFrame {

    /**
     * Creates new form Cajones_en_uso
     */
    public Cajones_en_uso(int ID) {
        con= new Conector();
        initComponents();
        this.setLayout(null);
        this.ID=ID;
        //initArray();
        setClock();
        initArray();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Vista de Seguridad");
        IDemp.setText(String.valueOf(ID));
        String name,apPat,apMat;
        System.out.println(ID);
        name=con.getValor("select nombre from empleado where idEmp="+ID+" ;");
        apPat=con.getValor("select ap from empleado where idEmp="+ID+" ;");
        apMat=con.getValor("select am from empleado where idEmp="+ID+" ;");
        Nombre.setText(name);
        aP.setText(apPat);
        aM.setText(apMat);
        timer = new Timer(10000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizar.doClick();
            }
        });
        timer.start();
        
    }
    
     private void setClock() {
        this.add((new clock(1030, 100, "labelClock")).getLbl());
    }
     
     private void initArray() {
        arr = new ArrayList<>();
        int i;
        for (i = 0; i != 20; i++) {
            arr.add(new ArrLabels(20 + (i * 50), 20, "A" + i, false, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 20; i != 40; i++) {
            arr.add(new ArrLabels(20 + ((i - 20) * 50), 100, "B" + (i - 20), true, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 40; i != 60; i++) {
            arr.add(new ArrLabels(20 + ((i - 40) * 50), 250, "C" + (i - 40), false, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 60; i != 80; i++) {
            arr.add(new ArrLabels(20 + ((i - 60) * 50), 330, "D" + (i - 60), true, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 80; i != 100; i++) {
            arr.add(new ArrLabels(20 + ((i - 80) * 50), 480, "E" + (i - 80), false, i + 1));
            this.add(arr.get(i).getLbl());
        }
        for (i = 100; i != 120; i++) {
            arr.add(new ArrLabels(20 + ((i - 100) * 50), 560, "F" + (i - 100), true, i + 1));
            this.add(arr.get(i).getLbl());
        }
    } 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IDemp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        aP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        aM = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lf.png"))); // NOI18N
        jLabel1.setAlignmentY(40.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 391, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lf.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lf.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 498, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lane_lines.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lane_lines.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setText("Apellido M.:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, 70, 40));

        IDemp.setEditable(false);
        getContentPane().add(IDemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 80, -1));

        jLabel8.setText("ID empleado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, -1, 40));

        Nombre.setEditable(false);
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, 80, -1));

        jLabel9.setText("Nombre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 280, 50, 40));

        aP.setEditable(false);
        getContentPane().add(aP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 80, -1));

        jLabel10.setText("Apellido P.:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 328, 70, 40));

        aM.setEditable(false);
        getContentPane().add(aM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 80, -1));

        actualizar.setText("Actualizar Vista");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:}
        int i;
        for (i = 0; i < 120; i++) {
            arr.get(i).updateView(i + 1);
        }
        System.out.println("Boton Presionado");
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDemp;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField aM;
    private javax.swing.JTextField aP;
    private javax.swing.JButton actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    private ArrayList<ArrLabels> arr;
    private int ID;
    private Conector con;
     private Timer timer;
}

